### ISSUE TITLE
Not sure if this is correct place to post

### ISSUE THREAD

**Issue by coffeespooner** [elmokki/nationgen#1074]
Love this program, really appreciate the hard work.  Got a couple quick questions about the search terms, hope someone could quickly answer.

1/ can I search for H3 priests?  Tried search for #magicskill 8 3 in unit command but doesn't seem to work
2/ could I search for, say Hoburg crossbows?
3/ could I search for an ethereal chariot?  Tried adding #ethereal and #chariot for unit search but doesn't return any.
4/ equally could I search for a size 5 trampler by combining search terms?
5/ I assume that some of the newer attributes like mason or formation fighter don't generate currently?

Like I said, such an awesome program.

**Comment by coffeespooner** [comment]
In nationwide filters - 2 similar entries.  Bug?

#new
#name "golem"
#chance 0.00625
#primarycommand "#stonebeing"
#command "#stonebeing"
#command "#ap -4"
#command "#prot +4"
#description "Stone skinned"
#end

#new
#name "golem"
#chance 0.00625
#primarycommand "#stonebeing"
#command "#stonebeing"
#command "#ap -2"
#command "#prot +2"
#description "Stone skinned"
#end

**Comment by Ealb** [comment]
This isn't the best place for general questions - that would be the thread over at DominionMods: http://dominionsmods.com/index.php?showtopic=3357

Re: your questions, I'm not sure what you mean by "unit search", so all questions involving that I'm not able to answer. Formation fighter is actually not new; it's been in Dominions (and NationGen) since Dom4. Mason can crop up on special commanders. The very-rare "golem" nation filters are intentionally similar, but it probably wouldn't hurt to call one "lesser" and the other "greater".
