### ISSUE TITLE
Summon Jaguar Toads spell error

### ISSUE THREAD

**Issue by wheriot** [elmokki/nationgen#1082]
Issue: Crash caused when I create a pretender when I load a nationgen mod when nation is generated with "Summon Jaguar Toad" spell.

Fix: Control F in .dm file to find Spell in question and change line:
#copyspell "Summon Jaguar Toad" to #copyspell "Summon Jaguar Toads"

**Comment by Ealb** [comment]
This is fixed in the dev version. The problem is a certain lack of motivation among devs to tie off a handful of loose ends needing resolved to push a new version out. There should be one in August (but not before mid-month at the earliest). On a marginally-more-positive note, it'll have more content because I tend to add new garbage when I feel guilty about not having enough motivation to do the fussy bits needing finished.

----- Reply message -----
