### ISSUE TITLE
Bad pixel, sidhe, bean, recolormask

### ISSUE THREAD

**Issue by DranKof** [elmokki/nationgen#1086]
nationgen/graphics/sidhe/bean/basesprite_recolormask.png

Has a pixel (I think 31,48) that is a different color from the rest of the clothing so when recoloring (colorizing, increasing saturation), it alone is completely different from the outfit. It doesn't look intentional. I'd suggest making it match the pixel down and left by one.

**Comment by Ealb** [comment]
I looked and I can't see this. 31, 48 (and all the pixels around there, and everywhere else) is an opaque grey in the same scale as the rest of the recolormask and I can't see what you'd mean. Unless you mean 31, 59 at the very bottom of the dress, which is the tip of the mostly-out-of-sight bare foot and is wholly intentional as it's copied from the source sprite (Morgan Sorceress's attack pose, IIRC).

**Comment by DranKof** [comment]
![image](https://user-images.githubusercontent.com/20900852/77196266-3681a880-6aa0-11ea-89c0-2c5d468f7353.png)

**Comment by Ealb** [comment]
Got it. Weird. I've had instances where Gimp's desaturation function doesn't affect everything, and I'm guessing this was the case here.
