### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by JAM-564** [elmokki/nationgen#1179]
Given that the text files that have instructions are about two years old and the fact that the syntax seems completely different now, I think it would be nice to either update the text files or some other way to see how to check or add code to natgen. On the note of syntax not working I should mention that I have very little coding experience. Even still, stuff like this looks wrong:

> #new
> #name "berserklow"
> #type "berserk"
> #basechance 0.5
> #command "#berserk +1"
> #chanceinc "magic nature 1"
> #chanceinc "command #berserk 10"
> #tag "nopose ranged"
> #tag "nopose mounted"
> #command "#gcost +1"
> #description "can enter berserker rage"
> #end

I thought this might be better, but I have no idea if it will work because, y'know, the documentation is 2 years old: 

> #new
> #name "berserklow"
> #type "berserk"
> #basechance 0.5
> #command "#berserk +1"
> #command "#gcost +1"
> #chanceinc anymagic 6 +1 
> #chanceinc personalcommand #berserk +10 
> #chanceinc posetag ranged *0 
> #chanceinc posetag mounted *0 
> #description "can enter berserker rage"
> #end

So overall, I guess I am looking for either a place to ask more questions like this or something to read that explains what commands natgen takes.  Mainly just an issue about outdated documentation, though.

**Comment by elmokki** [comment]
As for syntax, both #chanceinc stuff and #chanceinc "stuff" should work fine. It's one of the older files an has syntax that was needed at that point.

Now, some other points, although I have to admit I am not 100% certain on what I've done years ago anymore:

- #tag "nopose ranged" should be the same as #nopose ranged. 
- This differs from #chanceinc posetag ranged *0 in the sense that the chanceinc targets poses with tag "ranged". Most ranged poses don't have it explicitly tagged. I do admit that doing this with a chanceinc would be more consistent.

- chanceinc personalcommand and chanceinc command have different meanings that matter here.
- With personalcommand, getting +1 berserk would be 10 times as likely if the elite unit in question already has berserk. A pretty rare thing.
- With command, getting +1 berserk is 10 times as likely if any unit on the nation already has berserk. Generation order matters here: Elites are generated after mages, priests, normal troops and sacreds. If any of them got it, 

- chanceinc anymagic is a bit stricter than chanceinc magic. Anymagic does not allow random access at all, while magic allows "semi-reliable" random access, whatever I considered that to be when coding the system.

The documentation should actually not be outdated. It's a bit crap and doesn't cover everything, but I don't think any part in it is wrong. 

Anyway, for reference since I didn't find it from the docs, here's the order of generation:

1. Choose colors
2. Choose races (always primary and secondary, primary first)
3. Generate mages
4. Generate priests
5. Generate basic troops
6. Generate sacreds and elites
7. Generate scouts
8. Generate special commanders
9. Generate Gods
10. Figure out forts
11. Generate heroes
12. Apply nation wide filters (every unit has +1 strength and stuff like that)
13. Generate commanders (this copies sacreds and normal troops and makes commander versions of them)
14. Generate monsters
15. Generate sites
16. Choose national spells
17. Generate flag
18. Get start terrain affignity
