### ISSUE TITLE
Crash on Reacquire mount

### ISSUE THREAD

**Issue by PeopleThief** [elmokki/nationgen#1208]
Whenever I have my commander reacquire a mount the game crashes with nagot gick fel! message.

**Comment by danieldelpercio** [comment]
I did a test and reacquired mounts with the nationgen mod active, was not able to replicate this error. Something else could be causing this error. Not really much to go on here, reopen the issue if you can provide more info.

**Comment by PeopleThief** [comment]
I have not been able to replicate this one so not sure what was happening, but having more consistent issues with various crashes saying such and such unit having a dead mount is the reason it crashed.

**Comment by danieldelpercio** [comment]
We've seen such errors happen to people, but we suspect it's an error with Dominions itself (the error seems similar to the one you'd get when starting the game with a mounted pretender, which has since been patched). Unless we have a clear way to reproduce it it's hard to figure out what's happening.
