### ISSUE TITLE
Aesthetics of hoburg special weapons

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#147]
![preview_198_winiolstadt](https://cloud.githubusercontent.com/assets/12613576/8691228/bcdcdeac-2a8d-11e5-8b3f-154c467a15d5.png)

I made the size-3 hoburgs' gas/flamethrowers underslung on their right arms, mostly for simplicity's sake. I'm not entirely sure I like how it looks; though it's not awful, it's certainly not great with some mainhand weapons, such as the flail above - possibly just with 2h weapons in general. If you could have a look in SpriteGen at some point and give your opinion, it would be appreciated.

**Comment by elmokki** [comment]
It's a bit hard to see anything but the fire (or at a closer look, is it the fire spewer that looks like the flail pole? The weapons in general just look a bit off there.) In this particular case I think the fire should be rendered below the flail. 

I think the special weapons would probably look better under the offhand since the way offhand is aligned on the sprite is far more forgiving. There's also nothing wrong in having them as weapons instead of extra bonus stuff.

**Comment by elmokki** [comment]
Someone on IRC pointed out that there is actually the wooden flail pole there - it's just quite indistinct.

**Comment by elmokki** [comment]
I'll test whether making it darker and rendering it below the weapon would be an improvement, but I'll have to run to the store now so if you are awake you might beat me to it.

**Comment by elmokki** [comment]
![offhand](https://cloud.githubusercontent.com/assets/1543974/8695098/d1479784-2aeb-11e5-8fd5-525b4981e783.png)

This is some testing I did

**Comment by elmokki** [comment]
12:20 < Elmokki> which one is best?
12:21 < Flypaper> either Behind Weapon+2pixels or Offhand
12:21 < siepu> move the flail anywhere else honestly
12:21 < Flypaper> they're the most 'legible' options
12:22 < Flypaper> a variant on Offhand with the flail held vertically in his right hand might work better, yeah
12:23 < Flypaper> it'll still be clearly "2-handed" if you make the handle long and fat enough :P
12:23 < siepu> behnd 2 px higher is best for me too

The offhand one has issues if there is a large shield. In general I like that or behind weapon 2 pixels higher the best.

**Comment by elmokki** [comment]
It might be a good idea to just scrap that being available for every configuration. Like, the offhand one is probably fine if the unit can receive no offhands.

**Comment by Ealb** [comment]
I'll screw around with it and probably move it to the offhand, although it'd look funny if there was a shield, so there may be more limits than just that needed. I was trying to avoid replacing the hand with it because I've long meant to make something like this but weaker for the size 2 ones, but this is noticeably stronger than what I'd been thinking of for that to the point where it would still seem reasonable for the "better" size-3 suits to have to give up a hand for it.

**Comment by elmokki** [comment]
We can alternatively make it choose the hand it is on by equipment. Or make it give shield for it. Or have it on main hand and redraw polearms suitably to be in a more vertical angle and potentially on offhand like the two handed swords (which looks a bit weird, but I know from experience that drawing a whole new pose for those is a lot of work for little gain. That's why Fomorians have the -entirely historical and plausible - halfsword grip on their twohanded swords. I'm not sure if in this case you could have the sword in right hand going over right shoulder behind the head though)

**Comment by Ealb** [comment]
The only way I think could do that is with an overlay (like e.g. how I dealt with spaulder weirdness for samurai armor with cloaks - gah, I think I might need to do that for hoburg samurai armor too, come to think of it). Even then, with the gears and wires it might look odd.

And yeah, an extra pose for 2h swords (and *maybe* clubs) is a huge pain - I, too, opted for the halfsword grip on my advanced humans' zweihanders to avoid that, so I have nothing resembling shame or reluctance to be flexible on this particular count. I did give minotaurs a separate pose, but I originally hadn't intended to and was either going to deprive them of greatswords or make them wield them halfsword like the advanced humans (and colossi... hmm, yeah, that seems to be getting pretty standard for me)... but then I whimsically pasted part of a banelord onto my mino base and fell in love with the look, and decided it'd be worth the misery.

I haven't actually had a look at this yet, since my dev time today ended up being that restructuring of hoburg graphics and, um, adding a hoburgbred theme. I anticipate having a long spell to attack this and other outstanding issues tomorrow, though, so this should still be ready with everything else for a Friday release.
