### ISSUE TITLE
Clockwork Ogre balance

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#204]
I was looking at the mod they use (0.6.2 one) for a game here http://www.desura.com/games/dominions-4-thrones-of-ascensions/forum/thread/elmokki-natgen-late-era/page/3#1054346

Clockwork ogres seem pretty popular. They're very expensive in terms of resources obviously though. They don't have the exhaustion and they're extremely hard to kill by any means. Might need a price increase to 100ish gold each at least since you'll probably never have gold constraints building them.

However, Sma-behdbach is the nation I was mostly concerned off. They have this Clockwork Ogre called Molten Sentinel that has #fear 5. I have no idea what has spawned that monstrosity since:
``--- Applied filters: minorfelemental, castlemaster, Infantry sacred, `` EDIT: It's a specialslot thing it seems

That honestly seems like something ludicrously ridiculously good. Fear is a fearsome effect on any unit you can mass even to a remote degree and fear +5 even more so. They are size 3 so you can stack two units in each square and each square thus gives 10 squares reduced morale (some stacking). That's massive. I'd go for fear +1 at most, and even that may be excessive. A better alternative might be a fear-inducing weapon.

**Comment by Ealb** [comment]
The issue with going below 5 is that, per the UI and per forum/personal testing (and very much in contradiction to the manual), any fear below 5 has no effect. My test was 50 normal size-1 hoburgs with Fear (4) - they did not reduce hostile morale at all and were routed by 10 PD, but when I changed them to Fear (5) and replayed the same battle they easily routed the PD, with hostile troops showing stacked morale as low as -53. The modding manual alludes to this by stating that 5 is the default value. It's changed from Dom3; you can look at e.g. Horror Helms that went from giving Fear (0) to Fear (5), and there's no unit in the game with fear below 5. Which kinda makes sense when you look at the game manual explanation vs. the modding manual; per the former, Fear (0) gave a 6 square radius against 10 morale, with one harder morale check per 5 fear (i.e., fear as we knew it in Dom3). Per the latter, it's *one random square* per level and makes no mention of increased penalties, but testing shows they're definitely there.

Incidentally, the above is why all the mage filters and mounts like nightmares have fear (5) - anything less is literally worthless. I only figured that out around 0.5.0.9 or 0.5.0.10 (and discovered that Dom3-style Awe(0) had likewise become non-functional, and bumped the Awe filters by 1 simultaneously).

Having said that, if you have balance concerns, so do I, and I'm quite open to the idea of nerfing or even nixing the fear - I'm nothing resembling attached to it, and it was a late addition while scraping my brain for graphic-free special items so I could add them at the last minute. I went with *1.2 gold, but bumping that up to either a fixed increase or a higher multiplier would be entirely reasonable. They're actually very much like demon knights on a number of levels, and I'm not so sure I'm willing to see a nation with multiple forts building sacred 6-8 demon knights per turn - or even one fort building that. Artificial per-turn recruitment caps could be imposed (1-3/turn being the most reasonable-feeling mechanically); is there a per-pose (rather than per-race) command to weight random elites/sacred to be more likely to be cap-only? O/w, again, just getting rid of it is the easiest option.

I'm also open to a general increase in clockwork prices - their current prices kinda reflect how much of a trap they used to be, but the recent changes and/or just the bigger, tougher ones don't seem to have that problem. I can certainly see plump, arrogant hoburg clockwork jockeys demanding extravagant wages for their services...

**Comment by Ealb** [comment]
Since they're supposed to be causing fear via loud, skreeching, grinding gears increased encumbrance/fatigue and/or lowered movement could also be reasonable nerfs short of axing the fear, probably in concert with a price increase.

**Comment by elmokki** [comment]
#sacredratingmulti and #sacredcostmulti should work on poses, themes and filters as well as races. Most of the new commands use getAllUnitTags which gets all of those if feasible. 

I actually think that forcing them cap only and/or limited recruitment is probably good enough.

**Comment by Ealb** [comment]
First pass at balancing committed:

+10 rcost
#sacredratingmulti *0.75
#sacredcostmulti *1.25
Fear *1.2 gcost -> *1.25 gcost
Minimum 0.9 chance of caponly

**Comment by elmokki** [comment]
I posted this to commit as well, but:

I think some restrictions on what sacred stuff they can get should actually happen as well. I can do it eventually. Shapeshifts in general, except maybe the elemental ones, don't make a lot of sense and some things like glamour and maybe ethereal are a bit too much.

However, I kinda think that first I'll divide the sacred filters to a pile of separate files so we won't have so much redundancy. It's really stupid how now many filters are in three different files. A slight code change would allow having any amount of defaults if no specific filters are specified anyway.

**Comment by Ealb** [comment]
Well, a few patches back I went through most of the non-elemental mage transformations and added #chanceinc "personalcommand #mounted *0" - some of the sacreds got it at the same time, but it would probably be reasonable to add it to all of them, especially since the secondshapes don't always play nice anyway.

**Comment by Ealb** [comment]
I'm going to tentatively close this, with the assumption it'll be revisited if the last round of adjustments proves insufficient.
