### ISSUE TITLE
Nation descriptions are not showing in some mods

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#321]
In the current version, with dynastic humans basechance at 10000, a 40-nation mod for
seed -1646981592 with settings 1 will produce 40 nations whose descriptions can't be read in-game. I've tested the first nation alone, and with a mod size of 2, and in both of those cases the descriptions show up fine. Current very unpleasant debugging plan appears to be to continue adding nations to the mod until I find the size that breaks it, and then figure out what it's screwing up in the .dm above the nation description, because the nation description portions of both sizes of mods seem fine.

**Comment by Ealb** [comment]
Whatever is going on is pretty seriously messed up, but in a very subtle way. I'm really at a loss here. I found that I can start having problems with the above mod down around nation 133 - in a 35-nation version, all will be fine for 100-132, but 133 and 134 won't display nation descriptions and summaries in-game. If I pull out the seeds for those two (or even 132-134), the relevant portion of the .dm looks essentially the same (unit numbers are different, obviously) but descriptions and summaries will display in-game. If I make it with 40 nations, however, every nation in the mod will fail to display summaries.

If I make other mods with the same number of nations, they don't have these problems. Something very strange is going on, but I'm not having any luck tracking it down.

**Comment by elmokki** [comment]
Theoretically it could be that the game starts being problematic with a big enough number of strings in a mod or something like that. Then again the crash bug with ill defined monsters is kind of telling that it might be in our end as well.

This happens at various nation amounts with different settings. With settings integer 0 and same seed 38 is the treshold before errors. Similarly at 38 and seed -1 last couple of nations don't have descriptions. After removing the 10000 basechance from dynastic humans the seed -1 does not break at 38, but at 45 the last nations are broken again.

I would not worry about this until it starts happen early. It could very well be Dominions related instead of NationGen problem, even if it is a bit bizzarre that unit descriptions don't seem to be affected. 

Also:
CRITICAL FAILURE, IMAGE FILE /graphics/weapon/standard/coral_spear.png CANNOT BE FOUND.

**Comment by Ealb** [comment]
The 4.27 patch fixed this, didn't it?

**Comment by elmokki** [comment]
Probably

**Comment by Ealb** [comment]
Tested with a size-75 mod. No missing descriptions in evidence. I'll go ahead and close this.
