### ISSUE TITLE
Proper Foulspawn nations? Maybe?

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#399]
> 2016-01-27 18:09:01 +0100
Modding: first/secondshape can now use negative montag values

So this is forthcoming. If I understand things correctly, this could allow for recruitment of random ranges of specific Foulspawn from a single recruitable unit "template"...

**Comment by elmokki** [comment]
I'll definitely add functionality for this when it is released. It's really simple to be honest:

1. `#montagpose <pose>` to list possible sub-poses
2. `#montagpose_min`,` #montagpose_max` to set minimum and maximum amount of varieties. Alternatively it just generates one unit per `#montagpose` line and `#montagpose` has a chance argument. That way you can control it better to ever produce certain amount of certain types of units at most.
3. The target poses probably have `#basechance 0` and `#chanceinc posetag blabla 1` or something similar so that those poses aren't generated as units for roster itself
4. Probably some code unit  roster size related code so that you'll only get a few recruitable foul spawn troops since the variety is within unit
5. Something to track montag values and general handling so that the units are actually written to files. It's probably easiest to clump them to troop arrays and add functionality to tag them as units you can't recruit.

So basically you make a "foul spawn infantry" pose that looks like whatever. Maybe it's a ranged foul spawn with a big question mark over it or something. That one has `#firstshape -<montag> ` when generated and then there are x random units from whatever poses you defined generated absolutely randomly with `#montag <montag>`. From what I know this should result in random unit recruitment.

I suppose a proper foul spawn nation would have like 3 to 10 different base poses that contain more or less overlapping content and like 2-5 would be given to a nation. I really like the idea that you can try to recruit for example heavy infantry or archers or beasts, but you could end up with pretty much anything. 

In a sense an alternative would be to just generate a ton of units and weigh them differently for different recruitable units, but as you can afaik only have one montag per unit and the only way to weigh montag probabilities is to have duplicate units within montag, that would mean having a copy of each unit for each base pose and having multiple copies of each unit for each pose to account for weighing. Not a good idea for NationGen especially. I'd try to limit it so that you won't use hundreds of unit ids for one nation. Just 10 alternative results from 3 or 4 units is plenty.

**Comment by elmokki** [comment]
Actually mages etc might be handleable relatively easily if MontagUnitGen is a separate class. Essentially you'd just need to handle the sub-units at a suitable spot so that you can easily give them magic paths, commander commands etc. However, for unit id / sprite limit I'd say the amount of varieties generated for commanders should be small or none.

**Comment by Ealb** [comment]
Having "commander castes" with little or no randomness seems reasonable, yeah.

JK was recently asking the modding community if there were any easily implemented commands that they were lacking; I wonder if it would be easy enough to implement something like "multiple copies of a montag on a unit increases that unit's weight w/in a montag" that something like that would be worth requesting...

**Comment by elmokki** [comment]
Ideally you could have multiple montags to put unit in multiple categories AND #montag <id> <weight>, but I assume those are not tiny things. Then again I am pretty sure crossbreeding has some sort of weights on units so who knows, maybe?

**Comment by elmokki** [comment]
Oh, and there is the question of execute order whether `#firstshape` really happens after recruitment, but I think some of those Dom3 mods which had commanders with retinues already used #firstshape to shift to a form that doesn't summon units at turn start.

**Comment by elmokki** [comment]
4.23 is out. I plan to implement the code for this during the weekend at latest. As for foul spawn graphics it's a question whether the vanilla foul spawn style is preferable over humans-with-mutations kind of style.

**Comment by elmokki** [comment]
#409 contains this. Bugs in it or feature requests should probably be new, separate issues.
