### ISSUE TITLE
Foul spawn graphical style and plans

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#411]
I think I'll make some graphics for this stuff as it's been on wishlist to do for a long time, but you are probably better at graphics and my motivation probably won't allow me to make justice for the potential at all. 

The question is whether we use the base game style which is smaller-than-human size or whether we use the style I planned back in Dom3 days:  http://koti.kapsi.fi/elmokki/dom3/unitgen/foulspawn.png

I would imagine that any number of poses can be made and `#maxunits` can just be set to very low for poses with low amount of choices, but the amount of possible categories probably has to be a bit limited, like

- Light infantry
- Heavy infantry
- Ranged
- Beasts
- Cavalry
- Chariots
- Flyers

Then give like 3-4 of those for each nation.

I could also code some sort of method to make poses exclude other poses so some nations might for instance just have generic infantry with whatever level infantry units and that would exclude heavy/light infantry from generating. Also if there are different weights, for example low/medium/high mutation (low being less severe mutations and mismatch of equipment being weighed more common and high being tentacle monsters with or without weapons) for categories, those should probably be mutually exclusive.

**Comment by Ealb** [comment]
Hmm, honestly we could probably do both via themes that add specific poses to the nation; both styles have their own charms, the mutation parts would overlap a lot, and variety is the name of the game.

I have a directory with foulspawn candidate graphics sorted out somewhere or another, plus also some random unreleased abominations that can be repurposed in that regard (I'm thinking of my lizard-serpent and vanara-tiger "centaurs"... as well as the actual centaurs I was working on right now, I suppose). I'll try to dig those things up tonight.

**Comment by elmokki** [comment]
Oh yeah, obviously humans are only one aspect of foul spawns. I didn't even think of that. Oriental primate foul spawns or Hoburg foul spawns or Fomorian foul spawns all offer endless possibilities.

**Comment by Ealb** [comment]
![base_humanoid](https://cloud.githubusercontent.com/assets/12613576/13271248/d4f8f4ce-da61-11e5-87e6-0d01c647950b.png)

I'm going to go ahead and start doing some work on "small" foulspawn graphics. The above will be my "most human possible" point-of-departure - pretty much unit 458 without the grey dogleg/torso. I have a couple of ideas about how to cobble together units - probably by adding larm +rarm + lleg + rleg + head to a (torso) basesprite, and armor parts for each of those generated by a base armorfoo with multiple needs armorslotfoo armorfoo, and parts that would be unarmored by necessity (tentacles, etc.) rendering in the limbarmor slot instead of the limb slot.

**Comment by Ealb** [comment]
If filters weren't an issue, it would be quite entertaining to make 3-5 mage body chassis per nation and have FS mage recruitment be a matter of paying a recruitment cost based on paths and then having those paths secondshaped onto one of the bodies at random. It almost seems entertaining enough to suggest forgoing filters (or giving the all secondshapes mid-tier filters) so as to do this anyway...

**Comment by elmokki** [comment]
I had plans to add support to do this slightly differently. Basically if you had a mage with 100% random for BWND, you'd have a chassis for B, W, N and D alternatives separately. I just think this can't be done without events so it won't happen.

From what I understood what you want to do is to just make mage recruiting the same as troop recruiting but with magic paths locked to the original choice. If I got it right, it's not really that hard to make.

**Comment by Ealb** [comment]
Yep, pretty much. E.g., if a nation ends up with Tertiary T2, T1, T2a, T2b, T3a, T3b, assuming they're all Foulspawn then there'd be... hmm, let's say 4 unrecruitable "chassis" units generated (one per "style/level" rather than one per path set) either with tier-appropriate filters or universally tier-2 filters (the unit would have no personalmagic, I'd assume, so the filters would be generic, derived from unit commands, or derived from national paths), plus 6 recruitable "path template units" corresponding to the appropriate tiers, and the recruited units would secondshape their magic paths onto the appropriate shape upon recruitment. So effectively you'd end up with 6x4 unit + paths combinations of sweet, glorious chaos...

Hmm, or  possibly just create a fixed number (3-5) of mage "chassis units" for every FS nation, so even if you just have a single FS secondary mage, they'd still be unpredictable? With filter levels for each of the chassis either being random (default T1, with 50% chance to upgrade to T2, with 33% chance to upgrade to T3, for a 3:2:1 split?), or all T2?

**Comment by elmokki** [comment]
I might make something like this but for now it should be on hold. Once troops and sacreds are done graphically this should be easy to expand onto, but for now I would prefer to not bite too big of a chunk. We'll have to figure out how much current code needs to be tweaked for foul spawn troop rosters to be sensible and parts of that also matter for mages.

**Comment by Ealb** [comment]
Very understandable; I'm nowhere near ready for anything like this yet anyway. I'll keep plugging away at the basics for now.
