### ISSUE TITLE
Daevas and Yazatas

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#451]
Base on mostly IRC I'm pretty sure especially daevas are just overpowered. I think all these summonables-as-races races need to pretty much only get their super awesome stuff when they are elites or commanders and as a code thing I think all races/poses with really powerful innate stuff (fear, awe, glamour) need to just gain less and cost more in sacred generation. After all, getting something like glamour or awe tends to make a great sacred almost by itself.

**Comment by elmokki** [comment]
To elaborate, I think the summonables should be thought as elites of some level. I think normal troops should be slightly-better-than-average instead of super awesome. Though Tengus are size 2 I believe which already makes them ridiculously great.

**Comment by elmokki** [comment]
Also I believe I will just make all the super strong sacred features always cap only.

**Comment by Ealb** [comment]
Well, one easy place to start would be to eliminate the "pure daeva/yazata" themes, so when they show up it'd be Caelians plus supernatural elites/sacreds. The main reason that didn't happen in the first place was mostly a matter of symmetry, which is not nearly as important as balance.

If they're available as elites in addition to sacreds, it would probably be reasonable to impose a gold cost premium on the elite pose. You might be able to get more of them that way, but they'll cost a fortune. There also should probably be a lock to prevent them from getting slave tags since those halve upkeep now.

**Comment by elmokki** [comment]
I agree, but +3 att/def is way too much regardless. +1 or so might be okay, but the way att/def work they should get anything on top of +1 from the generation.

**Comment by Ealb** [comment]
...as much as it rankles my love of variety, I suppose semi-divine beings should probably only be sacred then. We're already doing that with Fomorian giants, after all.

**Comment by elmokki** [comment]
It's really the thing that was with Tengus as well. Getting them balanced and not ludicrously expensive is nigh impossible without sacrificing their power level.

**Comment by Ealb** [comment]
On the subject of summons-as-units, it *seems* like dust walkers are all right where they're at. I'm about 55 turns into a game with two nations of them (plus one of yazata), and the dust walkers are doing all right but not dominating.

**Comment by elmokki** [comment]
I heard a comment on them that was in the line of "they'd be really strong if they weren't undead" which sounds like an extremely good place to be.
