### ISSUE TITLE
Foul spawn category poses and sacredgen units.

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#468]
Currently they look the same. If the text is moved to armor or something chanceincs could work, but I believe that the best solution is to eventually have them as different poses in the first place. This is because while we may want to have "light infantry", "infantry" and "heavy infantry" options for troops (with infantry not spawning with either of the two alternatives because it essentially is it combined), there's way less point in constraining sacreds like this.

Also, these light/heavy infantry are probably doable with filters instead of separating the outcome poses. Similarly I think the smallest centauroids can be added to occasionally spawn as infantry with filters forcing only small animal parts to spawn. This needs a bit of a code update though so that the category pose can force a filter to the outcome poses or something.

**Comment by Ealb** [comment]
Generally on the subject of category/template units, does the current "fixed gcost/rcost" route I'd somewhat haphazardly gone seem like a good idea, or would we be better off with a function to average gcost/rcost from all the montag poses and assign that? Averages seem like it'd be better, if nothing else because it increases variation among FS nations...

**Comment by Ealb** [comment]
Oh god, just saw your posting of After the Cataclysm (which looks glorious in a horrible, "there went a couple of evenings I could have been working on NG" kind of way) - I can't believe I never actually saw FS PD in combat. I was sure I had, but I obviously just checked in the PD preview. Eww, eww, eww. 

*sigh* Well, I suppose this means FS aren't as close to being done as I'd hoped, and probably can't be released w/o at least a bit of fiddling with the PD code. I was seriously considering taking a stab at adding PD-only-pose functionality myself, so I might look at it... or I might not, since a lot of my enthusiasm for PD-only was so things like random longdead could be added as PD, which they obviously can't. If I'm overblessed with motivation I still might take a look, anyway.
