### ISSUE TITLE
A few small things that really need to be done at some point

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#505]
- Possibility to force sacreds to be cap only
- Possibility to for nation themes to increase cost of priests and mages somehow (Per pick of path? Just plain increase? I don't know. It's for #zombiereanim and such and allows some stronger reanims)

Both are really simple. Also #reclimit on sacred troop daevas is probably in order. I have no idea how high, but probably quite low. I hear they're pretty terrifying.

I may or may not do coding during June and July as I probably will be working way less. The less I need to write SQL to dig through data in SAS, the more I want to code Java. However, I will spend one week of June in Lapland and one in Germany so that takes quite a bit of time. Especially Germany isn't coding friendly.

**Comment by elmokki** [comment]
chaos rec can supposedly return more gold than units cost for cheapest units

**Comment by elmokki** [comment]
you can get full size air elementals for really cheap units (should be tied to unit size for one and increase cost drastically in the first place)

**Comment by Ealb** [comment]
On the last point, Air Elementals of any size are really powerful because they're a free turn-1 flier. I might be tempted to say that limiting any but the smallest elementals - size 2 at the most - to T3 might be reasonable.

For #zombiereanim, increasing priest price is probably a lost cause because if they're too expensive indy priests will be used instead. For #wightreanim and #horsereanim, (or #tombwormreanim, although that's mostly broken; #manikanreanim just plain doesn't work right now) the lower levels don't actually do anything, so indies are mostly not an issue.

**Comment by Ealb** [comment]
I'm not looking at any change in time I can pick away at things, but as usual, my issue is motivation more than time. Well, that and focus. It doesn't help when the only time I spend working on NG stuff is e.g. making ichtyid giants instead of finishing any of the half- or three-quarters-done stuff. (Sadly, true story - that's the only thing even vaguely NG-y I've done in like a week...)
