### ISSUE TITLE
Commanders and overlays

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#548]
Something odd is going on with commanders and overlays. Well, possibly just with non-standard slots in general.

1953658899 has three tier-3 mages with (wing) overlays but no wings. They should have both; all other (winged monkey) troops and lower-tier mages have both.

I don't have an example seed, but the first instances I saw of this was FS commanders with harp wings and (unneeded Yazata wing) overlays.

A very quick look the first time it cropped up didn't really make it obvious why it was happening. I'll probably poke at this more thoroughly over the weekend.

**Comment by Ealb** [comment]
I haven't been able to reproduce this since my example seeds broke, nor have I seen it crop up randomly for several releases, though it was never common. It also seems possible that this is the same thing  #648 addressed. I'm going to tentatively close this.

**Comment by elmokki** [comment]
I wasn't able to reproduce the seeds Bavarian Kid posted so I couldn't verify this actually helps, but considering how the overlay bug has ever happened only on commanders, chances are it's a mount being replaced and the old mount overlay being left over causing it.

This solution may not be optimal in terms of memory use, but it shouldn't be a huge memory hog either. I first wrote it without storing the previous item, but the issue was that you could break the graphics if you had an unit with separate leg graphics and some but not all armor requiring suitable leg graphics. In those cases switching from special leg graphic armor to a basic armor would've just removed the legs.

The hidden mini-bonus of this change is that spritegen works slightly better because previously if you had whatever with an overlay and swapped to a whatever without one, the overlay stayed in. This and the centaur fix were the first reasons to recompile spritegen in ages as well.

**Comment by elmokki** [comment]
...and checking at what Bavarian Kid just wrote, I may have broken something somehow.
