### ISSUE TITLE
Cleanup for 0.6.17

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#684]
Between the FS itemslot stuff I just uploaded, and the continued presence in 0.6.16x of the problem with conditionally generated mods retaining interim nation numbers (and thus not working much of the time unless regenerated from just the selected seeds), it feels like something should be pushed out. I'm not done dithering with serpents, but if I get inspired in the next day or so I might try to polish them off. O/w, I'm looking to push out what we currently have in a polished form (i.e., making sure anything half-implmented is disabled) as a mostly-just-code patch by Friday or so. There are a couple of bits of content, though, and it has been a month, so 0.6.17 seems better than 0.6.16d.

**Comment by Ealb** [comment]
TODO:
* new nationgen.jar
* new spritegen.jar
* update changelog
* ???

**Comment by elmokki** [comment]
Code quality looks just fine and yeah, 0.6.17 makes sense.

I've been meaning to start writing UW stuff, but it's a big chunk of code and also one that would warrant the rewriting of Roster/TroopGen to move the stuff selecting what exactly to generate to RosterGen (as opposed to currently choosing just race and role) and possibly rewrites to at least CommanderGen (it's kind of a mess and non-copy Commanders would be nice) and MageGen (a mess too). Especially Roster/TroopGen rewrite first would make sense since the way I imagined it makes RosterGen even more messy.
