### ISSUE TITLE
Custom monster graphic files

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#69]
I know you said this would be very easy, but it was more involved for me just because of my lack of deep familiarity with the code, particularly anything touching graphics. If it really is straightforward, this would be good to have, especially if we're about to get an influx of potential additions to monsters. Otherwise, it's not a huge priority and I'll take a look at it again eventually.

All this really should need to do is give monsters the same capacity as shapechange filters; i.e., specify a custom sprite, attack sprite (usually shift), and a recolormask. The monster directory has two versions of Avvite elephants that would serve as proof of concept, and the data files have sloppy, basechance 0 definitions for them.

**Comment by elmokki** [comment]
Apart from the attack sprite this would be two line thing at its simplest:

if(p.getItems("derp") != null)
  u.setSlot("derp", Entity.getRandom(n.random, p.getItems("derp")

and then add itemsets like you add to poses to monsters. They are actually poses. You could pretty easily also make just one item file "monstergraphics" and add a #usegraphic <name> that signifies the program to get that part instead of random one.

However, with attack sprites it becomes a bit more complex. Basically ShapeChangeUnits have the functionality of sprite copying already, so you'd make a ShapeChangeUnit with a monster with otherForm null and have the monsters as shapeshifts.

I'll do it at some point. I'm not at home for the next week or so starting from tomorrow so chances are I will code way less and work on data files if I do anything.

**Comment by Ealb** [comment]
I'm not sure if I'll get a lot done prior to the weekend, but I'll keep plugging away at getting a broad range of themes defined while simultaneously testing the new code.

**Comment by elmokki** [comment]
I can code the above, it's not a problem. It may take a while though.
