### ISSUE TITLE
Limits of hoburg technology (conceptual issue)

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#70]
So um. I kinda did a thing. It's not an issue per se, but I would like the opinion of someone less impulsive than me to look at it before I waste any more time on it. I was think about hoburg cultural themes. I'd already decided I wanted to do a Mesoamerican Mictlan-esque one mostly because of how many Central American mounts hoburgs have randomly gotten over the years. I then had the slightly-offkey notion to "balance" that with a Far East theme. That was pretty straightforward; four types of armor plus two helmets isn't that big of a deal, especially considering how few pose variants hoburgs use compared to some others. However, one thing led to another, and um:

![clockwork_armor2](https://cloud.githubusercontent.com/assets/12613576/8245673/0255b136-1600-11e5-970e-194078d8bee3.png)![clockwork_armor1](https://cloud.githubusercontent.com/assets/12613576/8245671/fff7dc20-15ff-11e5-94e8-cd4588056da7.png)![clockwork_ogre](https://cloud.githubusercontent.com/assets/12613576/8245652/63e186c4-15ff-11e5-8051-ff580d520b55.png) ![clockwork_ogre2](https://cloud.githubusercontent.com/assets/12613576/8245654/6720afe0-15ff-11e5-9621-51e074915c8a.png)![clockwork_armor1_oriental](https://cloud.githubusercontent.com/assets/12613576/8246894/7b1dca9a-1614-11e5-84c9-34acedb641fb.png)![clockwork_armor2_oriental](https://cloud.githubusercontent.com/assets/12613576/8246895/80159474-1614-11e5-8bd4-5655cc842351.png)

Assuming the sane voice doesn't say it's going too far to give hoburgs clunky impractically-resource-intensive size-3 probably-sacred-only clockwork mecha (that at the end of the day probably won't have more than 15hp, *maybe* 20hp; it's still just a hoburg in a steel can), uh, I'll probably tack the third one onto the industrial tech theme (well, and obviously the later ones would be for oriental + industrial neo-Jomonese hoburgs; as an aside, I found that oriental long+short syllables plus hoburg suffixes produce pleasing ridiculous nation names), though I may also shelf them for the moment IOT get some more basic theme data work done towards 6.0.0 rather than involving myself in potentially time-consuming spritework.

**Comment by elmokki** [comment]
Those look great and in the balance sense there is nothing wrong with those either. The oriental-industrial hoburg mech also is something that screams for a Godzilla monster.


I am likely to get no code written for a week now. I'm at girlfriends parents and her young nieces are making sure I won’t do much. So yeah, you have plenty of time before I have written the naming update.






From: Ealb
Sent: ‎Friday‎, ‎19‎ ‎June‎ ‎2015 ‎04‎:‎49
To: elmokki/nationgen





So um. I kinda did a thing. It's not an issue per se, but I would like the opinion of someone less impulsive than me to look at it before I waste any more time on it. I was think about hoburg cultural themes. I'd already decided I wanted to do a Mesoamerican Mictlan-esque one mostly because of how many Central American mounts hoburgs have randomly gotten over the years. I then had the slightly-offkey notion to "balance" that with a Far East theme. That was pretty straightforward; four types of armor plus two helmets isn't that big of a deal, especially considering how few pose variants hoburgs use compared to some others. However, one thing led to another, and um:

 clockwork_armor2  clockwork_armor1  clockwork_ogre   clockwork_ogre2 

Assuming the sane voice doesn't say it's going too far to give hoburgs clunky impractically-resource-intensive size-3 probably-sacred-only clockwork mecha (that at the end of the day probably won't have more than maybe 15hp; it's still just a hoburg in a steel can), uh, I'll probably tack those onto the industrial tech theme (well, and obviously the second one would be for oriental + industrial), though I may also shelf them for the moment IOT get some more basic theme data work done towards 6.0.0 rather than involving myself in potentially time-consuming spritework.

**Comment by elmokki** [comment]
also, conceptually having hoburgs of all cultures sounds very cool.

**Comment by Ealb** [comment]
As a preliminary step, I'm assigning hoburgs to N/S/E/W/central regions, with the rough correspondence being hoburg/Machakan/Jomon/Mictlan/Arco; it's probable that in the short term only oriental and occidental (and possibly austral) will see specific equipment added, but in the future more could of course be done to flesh out the variants of uniquely and distinctly annoying hoburg cultures

**Comment by elmokki** [comment]
I think that themeincs do not affect other themes in the same race. Chanceincs should work fine and is probably how you tied location and tech anyway.
Please put up an issue about this and I'll fix it later this week, hopefully.
22.6.2015 19.05 Ealb <notifications@github.com> kirjoitti:As a preliminary step, I'm assigning hoburgs to N/S/E/W/central regions, with the rough correspondence being hoburg/Machakan/Jomon/Mictlan/Arco; it's probable that in the short term only oriental and occidental (and possibly austral) will see specific equipment added, but in the future more could of course be done to flesh out the variants of uniquely and distinctly annoying hoburg cultures
