### ISSUE TITLE
Non-deterministic secondaryracecommands

### ISSUE THREAD

**Issue by Ealb** [elmokki/nationgen#74]
In re: the discussion in the thread about illithids, it seemed like this might be worth opening an issue for the purpose of discussing it regardless of whether or not anything gets implemented.

My first thought on this was - what about allowing the definition of secondary race posesets/posefilters/posefoos, by which I mean that either instead of "secondaryracecommand" - or possibly in addition to it, to allow for simpler secondaryracecommands for more straightforward things like Agarthan darkvision - it would be possible to set a chunk of commands on a per-role basis, and whenever the secondary race creates a troop of that role, it picks through all possible role-pose-filter-things with that role, assigns one according to all relevant probabilities, and then applies all the associated commands to the otherwise-normally-generated troop. Something like container classes for poses on secondary races, if that makes sense - basically at the end of the day a way to package up all the commands you want to apply to the secondary race and apply one set of them probabilistically whenever a race(1) unit is created by having different sets of commands for a given role ("slave infantry", "lobo infantry" for role infantry, or more generally "normal slave", "lobo slave" for all roles; only one eligible one of these gets picked), or breaking down commands by role (e.g. "slave monster" so your trogs, hydras, and sirrushes all have a slave tag, but not your secondary race troops (that's a very arbitrary example, but it's the first one that came to mind)), or both.

The eternal questions are of course if that'd be generally useful enough to merit implementation, whether there is a simpler/better/more robust alternative, or most generally whether it's worth the trouble to allow variable sets of commands for secondary races.

**Comment by elmokki** [comment]
I planned to do essentially the same or similar via the use of the troop filters. Like racial #freetroopfilter and theme-injected set of extra filters to pick from for the secondary race.
That should do the same, right?

25.6.2015 2.47 Ealb <notifications@github.com> kirjoitti:In re: the discussion in the thread about illithids, it seemed like this might be worth opening an issue for the purpose of discussing it regardless of whether or not anything gets implemented.

My first thought on this was - what about allowing the definition of secondary race posesets/posefilters/posefoos, by which I mean that either instead of "secondaryracecommand" - or possibly in addition to it, to allow for simpler secondaryracecommands for more straightforward things like Agarthan darkvision - it would be possible to set a chunk of commands on a per-role basis, and whenever the secondary race creates a troop of that role, it picks through all possible role-pose-filter-things with that role, assigns one according to all relevant probabilities, and then applies all the associated commands to the otherwise-normally-generated troop. Something like container classes for poses on secondary races, if that makes sense - basically at the end of the day a way to package up all the commands you want to apply to the secondary race and apply one set of them probabilistically whenever a race(1) unit is created by having different sets of commands for a given role ("slave infant
 ry", "lobo infantry" for role infantry, or more generally "normal slave", "lobo slave" for all roles; only one eligible one of these gets picked), or breaking down commands by role (e.g. "slave monster" so your trogs, hydras, and sirrushes all have a slave tag, but not your secondary race troops (that's a very arbitrary example, but it's the first one that came to mind)), or both.

The eternal questions are of course if that'd be generally useful enough to merit implementation, whether there is a simpler/better/more robust alternative, or most generally whether it's worth the trouble to allow variable sets of commands for secondary races.

**Comment by Ealb** [comment]
Yeah, that's pretty much what I was awkwardly describing.
