### ISSUE TITLE
Hoburg monsters

### ISSUE THREAD

**Issue by elmokki** [elmokki/nationgen#871]
#name "feral giant hoburg"
#basechance 0
#chanceinc "racetheme  boreal 1"
#chanceinc "racetheme  central 1"
#chanceinc "racetheme  imperial 0.5"
#chanceinc "racetheme  occidental 1"
#chanceinc "unittheme not feral *0"
#chanceinc "racetheme  fae *0"

I have no idea what the unittheme part it supposed to do, but I'm pretty sure it is always making the weights zero.

**Comment by elmokki** [comment]
There are some other issues too since occidental mammoths, for example, aren't showing up.

**Comment by elmokki** [comment]
Ooookay. #chanceinc racetheme is supposed to be for #theme foo in Race definitions, not something in the race theme filters. This is always empty for hoburgs.

The correct chanceinc is "hastheme" or "hasthemetheme" but seriously, I'll just make racetheme check it all because I don't think there will be any problems with that.

**Comment by elmokki** [comment]
Now that I read description of unittheme I get what you were after. It makes sense, but this one checks only #theme foo from places, not filter etc names.

**Comment by elmokki** [comment]
I have no idea how feral stuff is generated.

**Comment by elmokki** [comment]
I was also wondering about vine monsters but apparently the themes are disabled.

**Comment by Ealb** [comment]
Yeah, I'm totally not surprised all that is an awful mess. I *am* glad at least that there was some semblance of logic to why I did what I did even if the code didn't agree with my understanding of the documentation.

And I need to do vine stuff. That's like 2 or 3 years old at this point.

And, um, feral... at some point I had/thought I had/intended to make lowest-tech hoburg techlevel themes be "feral". Looking at the actual files, it's totally still primitive. I assume I didn't change it because of theme compatibility issues (or again, because I was convinced I already had), but hoburgs use the non-standard "agrarian" techlevel, so... easiest solution is to rename primitive as feral (or check for primitive instead of feral, I suppose).

**Comment by elmokki** [comment]
The #unittheme needs to be changed to #racetheme then, but yeah, that should make them work.

**Comment by Ealb** [comment]
I think I'll rename it to feral, then also have it add #theme feral and #theme primitive to the race, and have agrarian add #theme primitive as well. That would nicely balance compatibility and descriptiveness.

**Comment by Ealb** [comment]
#872 plus your broadening of the scope of #chanceing racetheme should take care of this.
