### ISSUE TITLE
Ichtyid Subraces Graphics

### ISSUE THREAD

**Issue by EnragedEggplant** [elmokki/nationgen#989]
Figured that it's better to post this here than in PMs on dom3mods.
I've been fooling around with NationGen and made several new ichtyid variants based on different fish species. Sprites are working, but I did not write any descriptions or mechanical differences. Just thought that this might be useful for you. Included a file with a list of all new and changed files and my comments. Feel free to use anything and/or change anything. I might make another batch later, if you'd like.

http://www.mediafire.com/file/3fkjze0uw5a7ill/ichtyids.rar/file

**Comment by elmokki** [comment]
These are great! I especially like the pikes. Perches, and probably clownfish, really need to have at least one or two units without chest armor per roster so that people see the coloration.  

I especially appreciate the fact that you bothered to make the definitions. These should be very trivial to add in now since all they need is some minor definition changes, so unless Ealb volunteers to do it, I guess I will do it eventually.

As for your questions:

> Are double spaces between #name and the theme names of cyprinid/koyid/etc intentional?

Whether they are or not, it should be all the same for code.

> Shouldn't it be "Draw sprite preview image" instead of review in the UI?

It probably should.

> not sure if I added the fire preference correctly

It's fine. It's not a huge boost though, which is not necessarily a bad idea of course. It doubles the weight for fire magic. Without other modifiers it'd mean that chance of fire being the first magic path of a nation being 1/8, it would be 2/9 (and second being fire if first wasn't, it would be 2/8 instead of 1/7 etc). In case of Ichtyids their race definition has weights 6 and 4 for water and nature respectively, so I suppose it could be 4 for the theme too.

> can preference for naked troops be added?

Not directly as far as I can remember, but you can wiggle such things in by, for example, making a naked chest armor very likely or adding a very likely pose that has only naked chest armor (and other limitations set in so the program doesn't try generating too many of them and fail). 

> I have included a recolor mask just in case of very rare non-orange clownfish, but I don't know how to reduce the chance of an alternate color scheme

You'd probably want to have two basesprites defined, one with recolormask and one without. Either these or racial themes would have #theme foo defined for each and the other would have chanceincs/themeincs setting the basechance of one 0 and the other whatever positive. This is if you want nations to have uniform colors. If not, just add another basesprite and use #basechance to set relative weights suitable and the program should generate somewhat random distribution of colors. Some things would always have the same color as other variants of that thing though. 

> berserk preference if not a base racial trait?

This sounds cool. Not sure if everyone should have berserking or whether it should just be something quite common. Could be for just troops and not commanders perhaps. Not sure if that's doable neatly or not, but the code changes should be minor as there is some loosely related code already in as far as I remember.

Bite attacks are another option, but extra attacks are probably scarier for balance than low strength berserk.

There are also now enough Ichtyid variants that perhaps there should be an option for rarer mixed Ichtyid nations. Especially piranhas and sharks fit well together as do pikes and perches. Could easily also just make them all mix.

**Comment by Ealb** [comment]
>  can preference for naked troops be added?
The way I normally handle this is adding a #themeinc naked *X and making sure there are various #theme naked armors defined such as e.g. naked, nekkid, starkers, nada, or nothing.

I haven't looked at these yet, but if there are already definitions that just need massaged, it should be viable for me to do a cleanup pass and get them up and running. My motivation isn't terribly high right now, but not having to do everything from scratch is always an incentive.

Re: berserking, I actually had to think some of this through for minotaurs, so depending on how things are defined, there are a couple of routes that could be taken.

**Comment by Ealb** [comment]
Hmm, in the "making work for myself" department, I now kinda wanna do a pass through this to add clubswords and such so we can have properly occidental piranhas...

**Comment by Ealb** [comment]
> I have included a recolor mask just in case of very rare non-orange clownfish, but I don't know how to reduce the chance of an alternate color scheme

If you want the race to have uniform colors, I'd just hijack the the existing mandatory pigmentation theme, and tag the uncolored basesprite as the generic "#theme common_pigment" and stack all the others on the colored basesprite  - that yields a roughly 1/8th chance of default coloration. Ofc, if there's a bunch more fish types with baked-in preferences for magic paths, the current pigmentation scheme needs adjusted anyway, because various pigmentations lead to different path weightings, which isn't perforce desirable. Although I suppose the demographic theme, since it should be picked before the pigment theme, could just add a themeinc to weight only towards the pigments desired. Yeah, that's probably what I'll do with these.

**Comment by elmokki** [comment]
Regarding naked troops, I think troops with absolutely gorgeous chests or backs should just generally get naked or near naked low level mages and priests.

**Comment by Ealb** [comment]
Since these will all have distinct poses by morphology, it's trivial to add a heavy #themeinc naked to those subraces' low-tier mages.

**Comment by Ealb** [comment]
Hmm... EnragedEggplant, if you get an itch to do more of these, what would you think of doing one based on flying fish?

**Comment by EnragedEggplant** [comment]
Sure, here.
http://www.mediafire.com/file/op2dpelqwtqbf9i/ichtyids2.rar/file
Not sure if I did everything right with the wings. There were some glitches during spriting, so I suggest testing the sprites out to see if everything works right.

Also, a bit of offtopic: I started making some satyr graphics and definitions. I'll send you them when I'm done, so you will have an easier time making them.

**Comment by Ealb** [comment]
...it'd be nice if there was a command for in-combat-only flight - like blessed flight, but w/o the bless. I suppose the solution will be to give flying fishmen (Cypselurids? Exocoetids?) flying, plus more-or-less the same mapmove as other ichtyids. Flight will also probably be a prot-conditional command, assuming I'm remembering the capabilities of that correctly.

I may massage some of the current names to make them less cumbersome, and I'll probably mangle the theme names into something more informative for documentation readability (e.g. "sharkmen", "perchmen", etc.). If I can avoid getting distracted, I should be able to integrate this by tomorrow.

Let me also add that I love that you've done the definitions. I worry sometimes that the current commandset is an opaque mess that only makes sense to Elmokki and me...

**Comment by Ealb** [comment]
...I haven't gotten to this yet, but I have an idea that I might be able to pull off to let sharks and piranhas be bitey (which it feels like they should be) w/o being particularly unbalanced. Essentially, give line troops a Savage/Untrained/Reckless/something-like-that bite that's #melee50 and also #skip or #skip2. If it works properly, on rounds where they bite (which should be half of 'em) they should have a reasonably strong chomp, but they would have 1 or 2 less "normal" attacks.

**Comment by Ealb** [comment]
> Not sure if I did everything right with the wings.

Finally getting around to properly looking at this. The problems you alluded to with wings are probably the absence of "#generateitem 1 wings" - without this a pose will not generate wings as they're not a normal slot. The overlay will be added automatically because the wings item has a #needs for it, though.

**Comment by elmokki** [comment]
To be fair, wings should possibly be just like mounts: Generated if they are available (units with randomness regardless them can use other slots or a "no wings" item)

**Comment by elmokki** [comment]
> Flight will also probably be a prot-conditional command, assuming I'm remembering the capabilities of that correctly.

I think that command uses encumbrance or is flexible. Should be trivial to edit it for whatever though.

**Comment by Ealb** [comment]
I'm thinking I might modify the selachids a bit - pretty much take the existing body and give it a flatter head that's more stereotypically sharky, and separately take the existing head and revise the body into something a bit more tuna-ish so as to make thunninids. I do hope that isn't objectionable to you, EnragedEggplant.

I may try to hack together istophorids (sailfish) and/or xiphiids (swordfish), but I'm not sure my spriting skills would do them justice.

**Comment by EnragedEggplant** [comment]
Sure, I have no objections. Looks like you've read my mind, as I had tuna, sailfish and swordfish already planned. Might make some sprites, since I have more free time now.

**Comment by Ealb** [comment]
If you want to take the lead on these, go ahead by all means. I daresay you're doing better than I am; looking on Wikipedia I REALLY wanna have a sailfish but I REALLY don't think I can do the fin justice.

The tuna one is mostly just because I see tuna every time I look at the shark because of its "nose" shape. ><

**Comment by Ealb** [comment]
I'll not mess with tuna graphics if you think you'll do them. The tweak I did to sharks was the nose and a bit more tail length:

![selachid_base](https://user-images.githubusercontent.com/12613576/41705266-7eba78c0-7506-11e8-9faa-1cc4f6f75e2b.png) vs. ![selachid_base2](https://user-images.githubusercontent.com/12613576/41705302-9a4083fa-7506-11e8-93e7-a3f4b8bffece.png)

**Comment by EnragedEggplant** [comment]
I like your version more. Looks more sharky.
I don't know how to make tuna look better, so I will leave that up to you.

**Comment by Ealb** [comment]
Looking at nation previews in Create a Pretender, 5 does indeed look to be standard for coral armor.

**Comment by EnragedEggplant** [comment]
Just noticed that hands_xiphiid.png is mistyped as hands_xipidd.png. Should be fixed.

**Comment by Ealb** [comment]
Went with slightly bigger head with mouth slightly agape, slightly longer tail. Like you, I'm not entirely pleased with them. They're visibly distinct, though, and not awful looking.

If I can bring myself to sit down and grind out some occidental weapons, this mess of fish should be about ready to serve up, unless you had any further inspirations.

**Comment by EnragedEggplant** [comment]
Things are looking great. I do not have any further inspirations for now, but might make some tropical fish someday in the future. Or enkidu.

**Comment by Ealb** [comment]
Enkidu probably aren't a ton of work, it's mostly a matter of doing some mage graphics (okay, and ideally female graphics), as almost all graphics for ogres will work for (and indeed, are based on) enkidu, with the only difference being that enkidu have slightly longer legs.

**Comment by Ealb** [comment]
Since this stuff is done and implemented, closing.
