### ISSUE TITLE
Satyr Stuff

### ISSUE THREAD

**Issue by EnragedEggplant** [elmokki/nationgen#993]
I noticed the lack of satyrs in NationGen, so I've decided to cut up some existing sprites and make some new ones to lay some groundwork for potential satyr implementation. The following archive has graphics for satyr base sprites, weapons, armor (no pants), some helmets. Three poses - normal, archer, crossbowman. Definitions are present for all items, except for the helmets. I hope this helps someday in the future.

http://www.mediafire.com/file/x4clkebkgwf6od6/satyrs.rar/file

**Comment by Ealb** [comment]
Thanks, it's been on my to-do list forever. Note that there is a vanilla unit that can serve as a basis for satyr cavalry in the form of the Blessed Couple - which also hits at something I'd like to do eventually, even if it'd be a bit involved because of dynamic second shapes: satyr troops riding centaur troops...

**Comment by Ealb** [comment]
Since I finally got off my lumpy, soft posterior and integrated this stuff, this can be closed. Sorry I took so damned long, @EnragedEggplant .
